"""Pure, stdlib-only building blocks for plugin-owned Sway configuration.

The module deliberately has no knowledge of model handlers or user configuration
locations.  Callers supply every path and every side-effecting dependency.
"""

from __future__ import annotations

from dataclasses import dataclass
import fcntl
import fnmatch
import hashlib
import json
import math
import os
import re
import shlex
import stat
import tempfile
from collections.abc import Mapping
from pathlib import Path
from typing import Any, Callable

_MANAGED_MARKER = "# hermes-sway-plugin: managed-v1"
_METADATA_PREFIX = "# hermes-sway-plugin: metadata="
_DIGEST_PREFIX = "# hermes-sway-plugin: sha256="


class PersistentConfigError(Exception):
    """Base failure for a plugin-owned configuration operation."""


class ConfigFormatError(PersistentConfigError):
    """The include is not a complete managed include."""


class ManualEditRefused(PersistentConfigError):
    """The managed body differs from the body last generated by the plugin."""


class CriteriaError(PersistentConfigError):
    """A declarative window matcher cannot be represented safely by Sway."""


class RuleRenderError(PersistentConfigError):
    """A persistent rule is incomplete or cannot be rendered safely."""


class CardinalityError(PersistentConfigError):
    """The current desktop cannot verify a rule's intended cardinality."""


class ConfigValidationError(PersistentConfigError):
    """Sway rejected a candidate or main configuration in check-only mode."""


class AtomicWriteError(PersistentConfigError):
    """A managed include could not be safely committed to disk."""


class ReloadRollbackError(PersistentConfigError):
    """Sway did not confirm a reload and restoration could not be confirmed."""


class DuplicateStartupEntry(PersistentConfigError):
    """A managed startup command duplicates an existing normalized command."""


@dataclass(frozen=True)
class IncludeConflict:
    kind: str
    source: Path
    line: int
    text: str


@dataclass(frozen=True)
class ConfigValidation:
    path: Path
    ok: bool
    stdout: str
    stderr: str


@dataclass(frozen=True)
class FileRevision:
    """Identity and content revision observed during one exact file read."""

    exists: bool
    device: int | None = None
    inode: int | None = None
    mode: int | None = None
    digest: str | None = None


@dataclass(frozen=True)
class AtomicWrite:
    target: Path
    candidate: Path
    backup: Path | None
    prior_bytes: bytes | None = None
    prior_mode: int | None = None
    prior_digest: str | None = None
    target_device: int | None = None
    target_inode: int | None = None
    target_digest: str | None = None


@dataclass(frozen=True)
class ReloadResult:
    reloaded: bool
    rolled_back: bool
    error: str | None = None


@dataclass(frozen=True)
class ManagedConfig:
    """The verified metadata and Sway body from one managed include."""

    metadata: dict[str, Any]
    body: str
    digest: str


@dataclass(frozen=True)
class CardinalityAudit:
    intended: str
    match_count: int
    matched_indices: tuple[int, ...]
    verified: bool


def _canonical_metadata(metadata: Mapping[str, Any]) -> str:
    if not isinstance(metadata, Mapping):
        raise ConfigFormatError("managed metadata must be an object")
    try:
        return json.dumps(dict(metadata), ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    except (TypeError, ValueError) as exc:
        raise ConfigFormatError("managed metadata is not JSON serializable") from exc


def _body_digest(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def render_managed_config(body: str, metadata: Mapping[str, Any]) -> str:
    """Render a deterministic, tamper-evident managed Sway include.

    The digest protects the emitted Sway body.  Metadata is canonical JSON so a
    future writer can safely compare it without depending on mapping order.
    """

    if not isinstance(body, str):
        raise ConfigFormatError("managed body must be a string")
    if "\x00" in body:
        raise ConfigFormatError("managed body cannot contain NUL")
    metadata_text = _canonical_metadata(metadata)
    return "\n".join(
        (
            _MANAGED_MARKER,
            _METADATA_PREFIX + metadata_text,
            _DIGEST_PREFIX + _body_digest(body),
            "",
            body,
        )
    )


def parse_managed_config(text: str) -> ManagedConfig:
    """Parse a renderer-produced include and refuse a manually changed body."""

    if not isinstance(text, str):
        raise ConfigFormatError("managed config must be text")
    header, separator, body = text.partition("\n\n")
    if not separator:
        raise ConfigFormatError("managed config is missing its header separator")
    lines = header.splitlines()
    if len(lines) != 3 or lines[0] != _MANAGED_MARKER:
        raise ConfigFormatError("managed config has an invalid header")
    if not lines[1].startswith(_METADATA_PREFIX) or not lines[2].startswith(_DIGEST_PREFIX):
        raise ConfigFormatError("managed config has an invalid metadata header")
    metadata_text = lines[1][len(_METADATA_PREFIX) :]
    try:
        metadata = json.loads(metadata_text)
    except json.JSONDecodeError as exc:
        raise ConfigFormatError("managed metadata is not valid JSON") from exc
    if not isinstance(metadata, dict) or _canonical_metadata(metadata) != metadata_text:
        raise ConfigFormatError("managed metadata is not canonical JSON object")
    digest = lines[2][len(_DIGEST_PREFIX) :]
    if len(digest) != 64 or any(char not in "0123456789abcdef" for char in digest):
        raise ConfigFormatError("managed config has an invalid sha256 digest")
    if _body_digest(body) != digest:
        raise ManualEditRefused("manual edit refused: managed Sway body checksum differs")
    return ManagedConfig(metadata=metadata, body=body, digest=digest)


# Short aliases keep the format API readable for callers which treat the include
# as a document rather than as a configuration object.
render_managed = render_managed_config
parse_managed = parse_managed_config


_CRITERIA_ORDER = (
    "app_id",
    "class",
    "instance",
    "title",
    "window_role",
    "window_type",
    "shell",
    "con_mark",
)
_CRITERIA_KEYS = frozenset(_CRITERIA_ORDER)
_PCRE_EXACT_SPECIALS = frozenset("\\.^$*+?{}[]|()")


def _escape_exact_pcre(value: str) -> str:
    return "".join("\\" + char if char in _PCRE_EXACT_SPECIALS else char for char in value)


def _sway_quoted(value: str) -> str:
    if "\x00" in value or "\n" in value or "\r" in value:
        raise CriteriaError("criterion value cannot contain a line break or NUL")
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_criteria(match: Mapping[str, Any]) -> str:
    """Render stable Sway criteria from explicit exact or regular-expression values.

    Exact text becomes an anchored PCRE expression.  ``regex`` deliberately
    leaves PCRE metacharacters intact, while both modes quote for Sway's config
    grammar rather than for a shell.
    """

    if not isinstance(match, Mapping) or not match:
        raise CriteriaError("at least one criterion is required")
    unknown = set(match) - _CRITERIA_KEYS
    if unknown:
        raise CriteriaError(f"unsupported criterion key: {sorted(unknown)[0]}")
    parts: list[str] = []
    for key in _CRITERIA_ORDER:
        if key not in match:
            continue
        specification = match[key]
        if isinstance(specification, str):
            value, mode = specification, "exact"
        elif isinstance(specification, Mapping):
            value = specification.get("value")
            mode = specification.get("mode", "exact")
            if set(specification) - {"value", "mode"}:
                raise CriteriaError(f"criterion {key} contains unsupported fields")
        else:
            raise CriteriaError(f"criterion {key} must be an object")
        if not isinstance(value, str) or not value:
            raise CriteriaError(f"criterion {key} value must be a non-empty string")
        if mode not in {"exact", "regex"}:
            raise CriteriaError(f"criterion {key} mode must be exact or regex")
        if key == "window_type":
            allowed_types = {
                "normal", "dialog", "utility", "toolbar", "splash", "menu",
                "dropdown_menu", "popup_menu", "tooltip", "notification",
            }
            if mode != "exact":
                raise CriteriaError("criterion window_type does not support regex mode in Sway 1.9")
            if value.casefold() not in allowed_types:
                raise CriteriaError("criterion window_type has an unsupported Sway 1.9 value")
            expression = value
        else:
            expression = "^" + _escape_exact_pcre(value) + "$" if mode == "exact" else value
        parts.append(f'{key}="{_sway_quoted(expression)}"')
    return "[" + " ".join(parts) + "]"


render_match_criteria = render_criteria


def _rule_text(value: object, label: str) -> str:
    if not isinstance(value, str) or not value or "\x00" in value or "\n" in value or "\r" in value:
        raise RuleRenderError(f"{label} must be a non-empty string without a line break or NUL")
    return value


def _rule_bool(value: object, label: str) -> bool:
    if not isinstance(value, bool):
        raise RuleRenderError(f"{label} must be a boolean")
    return value


def _rule_positive_int(value: object, label: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < 1:
        raise RuleRenderError(f"{label} must be a positive integer")
    return value


def _rule_quote(value: object, label: str) -> str:
    return '"' + _sway_quoted(_rule_text(value, label)) + '"'


def _render_border(border: object) -> str:
    if not isinstance(border, Mapping) or set(border) - {"style", "width"}:
        raise RuleRenderError("border must contain only style and optional width")
    style = border.get("style")
    if style not in {"none", "normal", "pixel"}:
        raise RuleRenderError("border style must be none, normal, or pixel")
    width = border.get("width")
    if width is not None:
        if isinstance(width, bool) or not isinstance(width, int) or width < 0:
            raise RuleRenderError("border width must be a non-negative integer")
        if style == "none":
            raise RuleRenderError("border none cannot have a width")
    if style == "pixel" and width is None:
        raise RuleRenderError("border pixel requires a width")
    return f"border {style}" + (f" {width}" if width is not None else "")


def _workspace_destination(name: object) -> str:
    """Render a workspace target as a Sway ``assign``/``move`` operand.

    Numeric names use the ``number`` form so Sway treats them as numbered
    workspaces; everything else stays a quoted name.
    """

    text = _rule_text(name, "destination workspace")
    if text.isdigit() and int(text) > 0:
        return "number " + text
    return _rule_quote(text, "destination workspace")


def render_window_rule(rule: Mapping[str, Any]) -> str:
    """Render one bounded window rule; require a matcher and visible outcome.

    Placement uses Sway's native ``assign`` criteria. ``for_window`` is reserved
    for commands that mutate the mapped view, and ``no_focus`` is rendered as its
    own top-level criteria command because it is not a runtime view command.
    """

    if not isinstance(rule, Mapping):
        raise RuleRenderError("window rule must be an object")
    match = rule.get("match")
    if not isinstance(match, Mapping):
        raise RuleRenderError("window rule requires match")
    try:
        criteria = render_criteria(match)
    except CriteriaError as exc:
        raise RuleRenderError(str(exc)) from exc
    destination = rule.get("destination", {})
    effects = rule.get("effects", {})
    if not isinstance(destination, Mapping) or set(destination) - {"workspace", "output"}:
        raise RuleRenderError("window destination can contain only workspace or output")
    if len(destination) > 1:
        raise RuleRenderError("window destination must choose workspace or output, not both")
    if not isinstance(effects, Mapping):
        raise RuleRenderError("window effects must be an object")
    supported_effects = {
        "floating", "width_px", "height_px", "center", "fullscreen", "sticky", "no_focus", "border", "opacity"
    }
    unknown = set(effects) - supported_effects
    if unknown:
        raise RuleRenderError(f"unsupported window effect: {sorted(unknown)[0]}")

    statements: list[str] = []
    if "workspace" in destination:
        target = _workspace_destination(destination["workspace"])
        statements.append(f"assign {criteria} workspace {target}")
    elif "output" in destination:
        target = _rule_quote(destination["output"], "destination output")
        statements.append(f"assign {criteria} output {target}")

    commands: list[str] = []
    for name, command in (("floating", "floating"), ("fullscreen", "fullscreen"), ("sticky", "sticky")):
        if name in effects:
            commands.append(command + (" enable" if _rule_bool(effects[name], name) else " disable"))
    if "width_px" in effects:
        commands.append(f"resize set width {_rule_positive_int(effects['width_px'], 'width_px')} px")
    if "height_px" in effects:
        commands.append(f"resize set height {_rule_positive_int(effects['height_px'], 'height_px')} px")
    if "center" in effects and _rule_bool(effects["center"], "center"):
        commands.append("move position center")
    if "no_focus" in effects and _rule_bool(effects["no_focus"], "no_focus"):
        statements.append(f"no_focus {criteria}")
    if "border" in effects:
        commands.append(_render_border(effects["border"]))
    if "opacity" in effects:
        opacity = effects["opacity"]
        if isinstance(opacity, bool) or not isinstance(opacity, (int, float)) or not math.isfinite(opacity) or not 0 <= opacity <= 1:
            raise RuleRenderError("opacity must be a finite number from 0 through 1")
        commands.append(f"opacity {opacity:g}")
    if commands:
        statements.append("for_window " + criteria + " " + ", ".join(commands))
    if not statements:
        raise RuleRenderError("window rule requires at least one effect or destination")
    return "\n".join(statements)


def render_workspace_output_rule(rule: Mapping[str, Any]) -> str:
    """Render a workspace-to-output assignment without any shell interpolation."""

    if not isinstance(rule, Mapping):
        raise RuleRenderError("workspace-output rule must be an object")
    if set(rule) - {"workspace", "outputs"}:
        raise RuleRenderError("workspace-output rule contains unsupported fields")
    workspace = _rule_quote(rule.get("workspace"), "workspace")
    outputs = rule.get("outputs")
    if isinstance(outputs, (str, bytes)) or not isinstance(outputs, (list, tuple)) or not outputs:
        raise RuleRenderError("outputs must be a non-empty list")
    rendered_outputs = [_rule_quote(output, "output") for output in outputs]
    if len(set(outputs)) != len(outputs):
        raise RuleRenderError("outputs must be unique")
    return "workspace " + workspace + " output " + " ".join(rendered_outputs)


def render_rule(rule: Mapping[str, Any]) -> str:
    """Dispatch a typed persistent rule to its one supported Sway statement."""

    if not isinstance(rule, Mapping):
        raise RuleRenderError("rule must be an object")
    kind = rule.get("kind")
    payload = {key: value for key, value in rule.items() if key != "kind"}
    if kind == "window":
        return render_window_rule(payload)
    if kind == "workspace_output":
        return render_workspace_output_rule(payload)
    raise RuleRenderError("rule kind must be window or workspace_output")


def audit_cardinality(
    match: Mapping[str, Any], intended: str, windows: list[Mapping[str, Any]] | tuple[Mapping[str, Any], ...], *, require_verified: bool = False
) -> CardinalityAudit:
    """Audit declarative matching against supplied current-window snapshots."""

    if intended not in {"one", "many"}:
        raise CardinalityError("intended cardinality must be one or many")
    # Validate exactly the same matcher accepted by the renderer before use.
    render_criteria(match)
    matched: list[int] = []
    for index, window in enumerate(windows):
        if not isinstance(window, Mapping):
            raise CardinalityError("window snapshots must be objects")
        matched_window = True
        for key, specification in match.items():
            value = window.get(key)
            expected = specification if isinstance(specification, str) else specification.get("value")
            mode = "exact" if isinstance(specification, str) else specification.get("mode", "exact")
            if not isinstance(value, str) or not isinstance(expected, str):
                matched_window = False
                break
            if mode == "exact" and value != expected:
                matched_window = False
                break
            if mode == "regex":
                try:
                    if re.search(expected, value) is None:
                        matched_window = False
                        break
                except re.error as exc:
                    raise CardinalityError(f"invalid regex for {key}: {exc}") from exc
        if matched_window:
            matched.append(index)
    count = len(matched)
    verified = count == 1 if intended == "one" else count >= 1
    audit = CardinalityAudit(intended, count, tuple(matched), verified)
    if require_verified and not verified:
        expectation = "one" if intended == "one" else "one or more"
        raise CardinalityError(f"expected {expectation} matching current window(s), found {count}")
    return audit



_RULE_CONFIG_NAME = "hermes-sway-plugin-rules.conf"
_RULE_MAIN_CONFIG_NAME = "config"
_RULE_FORMAT = 1
_RULE_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:-]{0,63}$")


@dataclass(frozen=True)
class ManagedRulePaths:
    """Explicit configured locations used by the plugin-owned rule include."""

    config_dir: Path
    main_config: Path
    include: Path


def resolve_managed_config_dir(config_dir: str | Path | None) -> tuple[Path, Path]:
    """Resolve the owned include directory and the Sway configuration it augments.

    An explicit ``config_dir`` names the Sway configuration directory to manage,
    so the owned include lives beside that configuration.  An empty setting uses
    the documented XDG default: includes under
    ``${XDG_CONFIG_HOME:-~/.config}/sway/hermes`` and the main configuration at
    ``${XDG_CONFIG_HOME:-~/.config}/sway/config``.  The plugin never edits that
    main configuration; it only reads it and recognizes safe literal paths, ``~``,
    relative paths, and filesystem globs that resolve to its managed include.
    """

    if config_dir in (None, ""):
        base = (os.environ.get("XDG_CONFIG_HOME") or "").strip()
        root = Path(base).expanduser() if base else Path.home() / ".config"
        sway_home = root / "sway"
        return sway_home / "hermes", sway_home / "config"
    if not isinstance(config_dir, (str, Path)):
        raise ConfigFormatError("config_dir must be a string or path")
    directory = Path(config_dir).expanduser()
    if not directory.is_absolute():
        raise ConfigFormatError("config_dir must be an absolute path")
    return directory, directory / _RULE_MAIN_CONFIG_NAME


def managed_rule_paths(config_dir: str | Path | None) -> ManagedRulePaths:
    """Resolve the owned rule include beside the Sway configuration it augments."""

    directory, main_config = resolve_managed_config_dir(config_dir)
    return ManagedRulePaths(directory, main_config, directory / _RULE_CONFIG_NAME)


def _copy_json(value: Any) -> Any:
    """Copy only JSON-safe resource values and expose deterministic representations."""

    try:
        return json.loads(json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":")))
    except (TypeError, ValueError) as exc:
        raise RuleRenderError("rule must contain JSON-compatible values") from exc


def _rule_id(value: object, *, rule: Mapping[str, Any] | None = None) -> str:
    if value is None:
        if rule is None:
            raise RuleRenderError("rule_id is required")
        digest = hashlib.sha256(_canonical_metadata(rule).encode("utf-8")).hexdigest()[:16]
        return "rule-" + digest
    if not isinstance(value, str) or not _RULE_ID.fullmatch(value):
        raise RuleRenderError("rule_id must use 1-64 letters, numbers, '.', '_', ':', or '-'")
    return value


def normalize_managed_rule(rule: Mapping[str, Any], *, allow_generated_id: bool = True) -> dict[str, Any]:
    """Validate, render, and canonicalize one persisted resource entry."""

    if not isinstance(rule, Mapping):
        raise RuleRenderError("rule entry must be an object")
    kind = rule.get("kind")
    if kind == "window":
        intended = rule.get("intended_cardinality")
        if intended not in {"one", "many"}:
            raise RuleRenderError("window rule requires intended_cardinality one or many")
        candidate = {
            "kind": "window",
            "match": _copy_json(rule.get("match")),
            "destination": _copy_json(rule.get("destination", {})),
            "effects": _copy_json(rule.get("effects", {})),
            "intended_cardinality": intended,
        }
    elif kind == "workspace_output":
        candidate = {
            "kind": "workspace_output",
            "workspace": _copy_json(rule.get("workspace")),
            "outputs": _copy_json(rule.get("outputs")),
        }
    else:
        raise RuleRenderError("rule kind must be window or workspace_output")
    # Rendering is also the complete grammar and bounded-effects validation.
    render_rule(candidate)
    rule_id = _rule_id(rule.get("rule_id"), rule=candidate if allow_generated_id else None)
    return {"rule_id": rule_id, **candidate}


def render_managed_rules(rules: tuple[Mapping[str, Any], ...] | list[Mapping[str, Any]]) -> str:
    """Render sorted resource entries into the one deterministic managed document."""

    normalized = [normalize_managed_rule(rule, allow_generated_id=False) for rule in rules]
    if len({rule["rule_id"] for rule in normalized}) != len(normalized):
        raise ConfigFormatError("managed rule metadata contains duplicate rule_id values")
    ordered = sorted(normalized, key=lambda rule: rule["rule_id"])
    body = "".join(render_rule({key: value for key, value in rule.items() if key not in {"rule_id", "intended_cardinality"}}) + "\n" for rule in ordered)
    metadata = {"format": _RULE_FORMAT, "resource": "sway_rule", "rules": ordered}
    return render_managed_config(body, metadata)


class ManagedRuleStore:
    """Stdlib-only managed resource facade for plugin-owned Sway rules."""

    def __init__(self, config_dir: str | Path) -> None:
        self.paths = managed_rule_paths(config_dir)

    def _load(self) -> tuple[list[dict[str, Any]], FileRevision]:
        include = self.paths.include
        try:
            raw, revision = _read_file_with_revision(include)
            if raw is None:
                return [], revision
            parsed = parse_managed_config(raw.decode("utf-8"))
        except (OSError, UnicodeError) as exc:
            raise ConfigFormatError(f"cannot read managed rule include: {exc}") from exc
        metadata = parsed.metadata
        if set(metadata) != {"format", "resource", "rules"} or metadata.get("format") != _RULE_FORMAT or metadata.get("resource") != "sway_rule":
            raise ConfigFormatError("managed rule include has unrecognized metadata")
        rules = metadata.get("rules")
        if not isinstance(rules, list):
            raise ConfigFormatError("managed rule metadata must contain a rules list")
        rendered = render_managed_rules(rules)
        expected = parse_managed_config(rendered)
        if expected.body != parsed.body:
            raise ManualEditRefused("manual edit refused: managed rules do not match metadata")
        return [_copy_json(rule) for rule in expected.metadata["rules"]], revision

    def list(self) -> list[dict[str, Any]]:
        return self._load()[0]

    def get(self, rule_id: object) -> dict[str, Any]:
        selected = _rule_id(rule_id)
        for rule in self.list():
            if rule["rule_id"] == selected:
                return rule
        raise ConfigFormatError(f"managed rule not found: {selected}")

    def preview(self, rules: list[Mapping[str, Any]]) -> str:
        return render_managed_rules(rules)

    def write(
        self,
        rules: list[Mapping[str, Any]],
        *,
        subprocess_run: Callable[..., Any],
        atomic_replace_fn: Callable[..., AtomicWrite] | None = None,
        backup_count: int = 3,
        sway_binary: str = "sway",
        expected_current: FileRevision | None = None,
    ) -> AtomicWrite:
        if isinstance(backup_count, bool) or not isinstance(backup_count, int) or backup_count < 0:
            raise AtomicWriteError("backup_keep must be a non-negative integer")
        if not self.paths.main_config.is_file():
            raise ConfigValidationError(f"configuration does not exist: {self.paths.main_config}")
        content = render_managed_rules(rules)
        self.paths.config_dir.mkdir(parents=True, exist_ok=True)
        return write_managed_include(
            self.paths.include,
            self.paths.main_config,
            content,
            subprocess_run=subprocess_run,
            atomic_replace_fn=atomic_replace_fn,
            backup_count=backup_count,
            sway_binary=sway_binary,
            expected_current=expected_current,
        )

    def _conflicts(self, new_rule: Mapping[str, Any]) -> tuple[IncludeConflict, ...]:
        """Refuse competing *external* rule statements unless explicitly allowed.

        The plugin-owned includes are never external: their statements are managed
        by this store, and the include lines themselves are configuration the user
        was instructed to add.
        """

        return scan_include_conflicts(
            self.paths.main_config,
            managed_include=self.paths.include,
            owned_includes=(self.paths.config_dir / _STARTUP_CONFIG_NAME,),
        )

    def add(self, rule: Mapping[str, Any], **write_kwargs: Any) -> dict[str, Any]:
        created = normalize_managed_rule(rule)
        existing, revision = self._load()
        if any(entry["rule_id"] == created["rule_id"] for entry in existing):
            raise ConfigFormatError(f"managed rule already exists: {created['rule_id']}")
        self.write(existing + [created], expected_current=revision, **write_kwargs)
        return created

    def update(self, rule_id: object, rule: Mapping[str, Any], **write_kwargs: Any) -> dict[str, Any]:
        selected = _rule_id(rule_id)
        updated = normalize_managed_rule({**dict(rule), "rule_id": selected}, allow_generated_id=False)
        existing, revision = self._load()
        if not any(entry["rule_id"] == selected for entry in existing):
            raise ConfigFormatError(f"managed rule not found: {selected}")
        self.write(
            [updated if entry["rule_id"] == selected else entry for entry in existing],
            expected_current=revision,
            **write_kwargs,
        )
        return updated

    def remove(self, rule_id: object, **write_kwargs: Any) -> dict[str, Any]:
        selected = _rule_id(rule_id)
        existing, revision = self._load()
        removed = next((entry for entry in existing if entry["rule_id"] == selected), None)
        if removed is None:
            raise ConfigFormatError(f"managed rule not found: {selected}")
        self.write(
            [entry for entry in existing if entry["rule_id"] != selected],
            expected_current=revision,
            **write_kwargs,
        )
        return removed


_STARTUP_CONFIG_NAME = "hermes-sway-plugin-startup.conf"
_STARTUP_MAIN_CONFIG_NAME = "config"
_STARTUP_FORMAT = 1
_STARTUP_ID = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.:-]{0,63}$")
_STARTUP_RUN_ON = ("sway_start_only", "sway_start_and_every_reload")
_STARTUP_RELAUNCH_WARNING = "config_rollback_cannot_terminate_launched_processes"


@dataclass(frozen=True)
class ManagedStartupPaths:
    """Explicit configured locations used by the plugin-owned startup include."""

    config_dir: Path
    main_config: Path
    include: Path


def managed_startup_paths(config_dir: str | Path | None) -> ManagedStartupPaths:
    """Resolve the owned startup include beside a caller-supplied main config."""

    directory, main_config = resolve_managed_config_dir(config_dir)
    return ManagedStartupPaths(directory, main_config, directory / _STARTUP_CONFIG_NAME)


def _startup_argv(argv: object) -> list[str]:
    if isinstance(argv, (str, bytes)) or not isinstance(argv, (list, tuple)) or not 1 <= len(argv) <= 64:
        raise RuleRenderError("argv must contain 1 to 64 strings")
    if any(not isinstance(item, str) or not item or "\x00" in item or "\n" in item for item in argv):
        raise RuleRenderError("every argv element must be a non-empty single-line string")
    return list(argv)


def render_startup_entry(entry: Mapping[str, Any]) -> str:
    """Render one startup command as a shell-safe Sway ``exec`` statement.

    ``exec`` runs when Sway starts.  ``exec_always`` also reruns the command on
    every configuration reload, so it is only ever rendered for an explicitly
    acknowledged entry.
    """

    if not isinstance(entry, Mapping):
        raise RuleRenderError("startup entry must be an object")
    argv = _startup_argv(entry.get("argv"))
    run_on = entry.get("run_on")
    if run_on not in _STARTUP_RUN_ON:
        raise RuleRenderError("run_on must be sway_start_only or sway_start_and_every_reload")
    keyword = "exec" if run_on == "sway_start_only" else "exec_always"
    return keyword + " " + shlex.join(argv)


def normalize_managed_startup(entry: Mapping[str, Any], *, allow_generated_id: bool = True) -> dict[str, Any]:
    """Validate, render, and canonicalize one persisted startup entry."""

    if not isinstance(entry, Mapping):
        raise RuleRenderError("startup entry must be an object")
    candidate = {
        "argv": _startup_argv(entry.get("argv")),
        "run_on": entry.get("run_on"),
    }
    if candidate["run_on"] not in _STARTUP_RUN_ON:
        raise RuleRenderError("run_on must be sway_start_only or sway_start_and_every_reload")
    render_startup_entry(candidate)
    entry_id = entry.get("entry_id")
    if entry_id is None:
        if not allow_generated_id:
            raise RuleRenderError("entry_id is required")
        digest = hashlib.sha256(_canonical_metadata(candidate).encode("utf-8")).hexdigest()[:12]
        entry_id = "startup_" + digest
    elif not isinstance(entry_id, str) or not _STARTUP_ID.fullmatch(entry_id):
        raise RuleRenderError("entry_id must use 1-64 letters, numbers, '.', '_', ':', or '-'")
    return {"entry_id": entry_id, **candidate}


def render_managed_startup(entries: tuple[Mapping[str, Any], ...] | list[Mapping[str, Any]]) -> str:
    """Render sorted startup entries into the one deterministic managed document."""

    normalized = [normalize_managed_startup(entry, allow_generated_id=False) for entry in entries]
    if len({entry["entry_id"] for entry in normalized}) != len(normalized):
        raise ConfigFormatError("managed startup metadata contains duplicate entry_id values")
    ordered = sorted(normalized, key=lambda entry: entry["entry_id"])
    body = "".join(render_startup_entry(entry) + "\n" for entry in ordered)
    metadata = {"format": _STARTUP_FORMAT, "resource": "sway_startup", "entries": ordered}
    return render_managed_config(body, metadata)


class ManagedStartupStore:
    """Stdlib-only managed resource facade for plugin-owned startup commands."""

    def __init__(self, config_dir: str | Path) -> None:
        self.paths = managed_startup_paths(config_dir)

    def _load(self) -> tuple[list[dict[str, Any]], FileRevision]:
        include = self.paths.include
        try:
            raw, revision = _read_file_with_revision(include)
            if raw is None:
                return [], revision
            parsed = parse_managed_config(raw.decode("utf-8"))
        except (OSError, UnicodeError) as exc:
            raise ConfigFormatError(f"cannot read managed startup include: {exc}") from exc
        metadata = parsed.metadata
        if (
            set(metadata) != {"format", "resource", "entries"}
            or metadata.get("format") != _STARTUP_FORMAT
            or metadata.get("resource") != "sway_startup"
        ):
            raise ConfigFormatError("managed startup include has unrecognized metadata")
        entries = metadata.get("entries")
        if not isinstance(entries, list):
            raise ConfigFormatError("managed startup metadata must contain an entries list")
        expected = parse_managed_config(render_managed_startup(entries))
        if expected.body != parsed.body:
            raise ManualEditRefused("manual edit refused: managed startup entries do not match metadata")
        return [_copy_json(entry) for entry in expected.metadata["entries"]], revision

    def list(self) -> list[dict[str, Any]]:
        return self._load()[0]

    def get(self, entry_id: object) -> dict[str, Any]:
        selected = _startup_entry_id(entry_id)
        for entry in self.list():
            if entry["entry_id"] == selected:
                return entry
        raise ConfigFormatError(f"managed startup entry not found: {selected}")

    def write(
        self,
        entries: list[Mapping[str, Any]],
        *,
        subprocess_run: Any,
        atomic_replace_fn: Callable[..., AtomicWrite] | None = None,
        backup_count: int = 3,
        sway_binary: str = "sway",
        expected_current: FileRevision | None = None,
    ) -> AtomicWrite:
        return write_managed_include(
            self.paths.include,
            self.paths.main_config,
            render_managed_startup(entries),
            subprocess_run=subprocess_run,
            atomic_replace_fn=atomic_replace_fn,
            backup_count=backup_count,
            sway_binary=sway_binary,
            expected_current=expected_current,
        )

    def add(self, entry: Mapping[str, Any], **write_kwargs: Any) -> dict[str, Any]:
        created = normalize_managed_startup(entry)
        existing, revision = self._load()
        if any(item["entry_id"] == created["entry_id"] for item in existing):
            raise ConfigFormatError(f"managed startup entry already exists: {created['entry_id']}")
        duplicate = _duplicate_startup(existing, created)
        if duplicate is not None:
            raise DuplicateStartupEntry(
                f"an entry already starts the same command with run_on {created['run_on']}: {duplicate['entry_id']}"
            )
        self.write(existing + [created], expected_current=revision, **write_kwargs)
        return created

    def update(self, entry_id: object, entry: Mapping[str, Any], **write_kwargs: Any) -> dict[str, Any]:
        selected = _startup_entry_id(entry_id)
        updated = normalize_managed_startup({**dict(entry), "entry_id": selected}, allow_generated_id=False)
        existing, revision = self._load()
        if not any(item["entry_id"] == selected for item in existing):
            raise ConfigFormatError(f"managed startup entry not found: {selected}")
        remaining = [item for item in existing if item["entry_id"] != selected]
        duplicate = _duplicate_startup(remaining, updated)
        if duplicate is not None:
            raise DuplicateStartupEntry(
                f"an entry already starts the same command with run_on {updated['run_on']}: {duplicate['entry_id']}"
            )
        self.write([updated, *remaining], expected_current=revision, **write_kwargs)
        return updated

    def remove(self, entry_id: object, **write_kwargs: Any) -> dict[str, Any]:
        selected = _startup_entry_id(entry_id)
        existing, revision = self._load()
        removed = next((entry for entry in existing if entry["entry_id"] == selected), None)
        if removed is None:
            raise ConfigFormatError(f"managed startup entry not found: {selected}")
        self.write(
            [item for item in existing if item["entry_id"] != selected],
            expected_current=revision,
            **write_kwargs,
        )
        return removed


def _startup_entry_id(value: object) -> str:
    if not isinstance(value, str) or not _STARTUP_ID.fullmatch(value):
        raise RuleRenderError("entry_id must use 1-64 letters, numbers, '.', '_', ':', or '-'")
    return value


def _duplicate_startup(
    entries: list[Mapping[str, Any]], candidate: Mapping[str, Any]
) -> Mapping[str, Any] | None:
    key = (candidate["run_on"], tuple(candidate["argv"]))
    for entry in entries:
        if (entry["run_on"], tuple(entry["argv"])) == key:
            return entry
    return None


def write_managed_include(
    include: Path,
    main_config: Path,
    content: str,
    *,
    subprocess_run: Any,
    atomic_replace_fn: Callable[..., AtomicWrite] | None = None,
    backup_count: int = 3,
    sway_binary: str = "sway",
    expected_current: FileRevision | None = None,
) -> AtomicWrite:
    """Validate a rendered include beside the main config, then replace it atomically."""

    if isinstance(backup_count, bool) or not isinstance(backup_count, int) or backup_count < 0:
        raise AtomicWriteError("backup_keep must be a non-negative integer")
    if not Path(main_config).is_file():
        raise ConfigValidationError(f"configuration does not exist: {main_config}")
    include.parent.mkdir(parents=True, exist_ok=True)
    candidate: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "w", encoding="utf-8", dir=include.parent, prefix=include.name + ".candidate.", delete=False
        ) as handle:
            candidate = Path(handle.name)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        validate_candidate_and_main(candidate, main_config, subprocess_run, sway_binary=sway_binary)
        writer = atomic_replace if atomic_replace_fn is None else atomic_replace_fn
        return writer(
            include,
            content,
            backup_count=backup_count,
            expected_current=expected_current,
        )
    finally:
        if candidate is not None:
            candidate.unlink(missing_ok=True)


def include_target_matches_owned(directory: Path, target: str, owned_paths: set[Path]) -> bool:
    """True when an include target names one of the plugin-owned files.

    Both the documented glob (``~/.config/sway/hermes/*.conf``) and an explicit
    absolute or relative path are recognised, so the plugin never reports its own
    include line as an external conflict.
    """

    expanded = os.path.expanduser(target)
    if any(character in expanded for character in "*?["):
        pattern = Path(expanded)
        if not pattern.is_absolute():
            pattern = directory / expanded
        pattern_parts = pattern.parts
        return any(
            len(candidate.parts) == len(pattern_parts)
            and all(
                fnmatch.fnmatchcase(candidate_part, pattern_part)
                for candidate_part, pattern_part in zip(candidate.parts, pattern_parts)
            )
            for candidate in owned_paths
        )
    candidate = Path(expanded)
    if not candidate.is_absolute():
        candidate = directory / expanded
    try:
        return candidate.resolve() in owned_paths
    except OSError:
        return False


def scan_include_conflicts(
    main_config: str | Path,
    *,
    managed_include: str | Path,
    owned_includes: tuple[str | Path, ...] = (),
) -> tuple[IncludeConflict, ...]:
    """Conservatively scan literal includes without invoking a shell or Sway.

    Variable/glob/absolute includes are reported as unscannable rather than
    expanded.  The plugin-owned include itself is intentionally not inspected.
    """

    root = Path(main_config)
    owned = Path(managed_include).resolve()
    owned_paths = {owned, *(Path(item).resolve() for item in owned_includes)}
    found: list[IncludeConflict] = []
    visited: set[Path] = set()

    def visit(path: Path) -> None:
        path = path.resolve()
        if path in visited or path in owned_paths:
            return
        visited.add(path)
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except OSError:
            found.append(IncludeConflict("unreadable_include", path, 0, str(path)))
            return
        for number, raw in enumerate(lines, 1):
            statement = raw.strip()
            if not statement or statement.startswith("#"):
                continue
            lowered = statement.casefold()
            if lowered.startswith("for_window "):
                found.append(IncludeConflict("for_window", path, number, raw))
            elif lowered.startswith("assign ") or lowered.startswith("workspace ") and " output " in lowered:
                found.append(IncludeConflict("workspace_output", path, number, raw))
            if not lowered.startswith("include "):
                continue
            target = statement[8:].strip()
            if target and include_target_matches_owned(path.parent, target, owned_paths):
                continue
            if not target or target.startswith("/") or any(token in target for token in ("$", "~", "*", "?", "[", "]")):
                found.append(IncludeConflict("unscannable_include", path, number, raw))
                continue
            candidate = (path.parent / target).resolve()
            if candidate in owned_paths:
                continue
            visit(candidate)

    visit(root)
    return tuple(found)


def validate_sway_config(path: str | Path, subprocess_run: Any, *, sway_binary: str = "sway") -> ConfigValidation:
    """Run ``sway -C`` through an injected runner; never invoke a shell."""

    config_path = Path(path)
    if not config_path.is_file():
        raise ConfigValidationError(f"configuration does not exist: {config_path}")
    try:
        result = subprocess_run([sway_binary, "-C", "-c", str(config_path)], text=True, capture_output=True, check=False)
    except OSError as exc:
        raise ConfigValidationError(f"cannot execute {sway_binary}: {exc}") from exc
    stdout = getattr(result, "stdout", "") or ""
    stderr = getattr(result, "stderr", "") or ""
    if getattr(result, "returncode", None) != 0:
        detail = str(stderr or stdout or f"exit status {getattr(result, 'returncode', '?')}")
        raise ConfigValidationError(f"Sway configuration validation failed: {detail[:2000]}")
    return ConfigValidation(config_path, True, str(stdout), str(stderr))


def validate_candidate_and_main(candidate: str | Path, main_config: str | Path, subprocess_run: Any, *, sway_binary: str = "sway") -> tuple[ConfigValidation, ConfigValidation]:
    """Check both the proposed include-aware candidate and the main config."""

    return (
        validate_sway_config(candidate, subprocess_run, sway_binary=sway_binary),
        validate_sway_config(main_config, subprocess_run, sway_binary=sway_binary),
    )


def _read_file_with_revision(path: Path) -> tuple[bytes | None, FileRevision]:
    """Read one regular pathname and bind the bytes to its inode identity."""

    flags = os.O_RDONLY | getattr(os, "O_NOFOLLOW", 0)
    try:
        file_fd = os.open(path, flags)
    except FileNotFoundError:
        return None, FileRevision(False)
    try:
        file_stat = os.fstat(file_fd)
        if not stat.S_ISREG(file_stat.st_mode):
            raise OSError(f"not a regular file: {path}")
        with os.fdopen(file_fd, "rb") as handle:
            file_fd = -1
            content = handle.read()
        path_stat = os.stat(path, follow_symlinks=False)
        if path_stat.st_dev != file_stat.st_dev or path_stat.st_ino != file_stat.st_ino:
            raise OSError(f"file changed while it was read: {path}")
    finally:
        if file_fd >= 0:
            os.close(file_fd)
    return content, FileRevision(
        True,
        file_stat.st_dev,
        file_stat.st_ino,
        stat.S_IMODE(file_stat.st_mode),
        hashlib.sha256(content).hexdigest(),
    )


def _secure_backup_copy(content: bytes, mode: int, destination: Path) -> None:
    """Copy captured bytes through an owned inode before replacing a named backup."""

    temporary: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            "wb", dir=destination.parent, prefix=destination.name + ".tmp.", delete=False
        ) as temporary_handle:
            temporary = Path(temporary_handle.name)
            temporary_handle.write(content)
            os.fchmod(temporary_handle.fileno(), mode)
            temporary_handle.flush()
            os.fsync(temporary_handle.fileno())
        os.replace(temporary, destination)
        temporary = None
    finally:
        if temporary is not None:
            temporary.unlink(missing_ok=True)


def atomic_replace(
    path: str | Path,
    content: str,
    *,
    backup_count: int = 3,
    expected_current: FileRevision | None = None,
) -> AtomicWrite:
    """CAS, stage, back up, and atomically replace a managed include."""

    target = Path(path)
    if not isinstance(content, str) or "\x00" in content:
        raise AtomicWriteError("replacement content must be text without NUL")
    if backup_count < 0:
        raise AtomicWriteError("backup_count cannot be negative")
    if expected_current is not None and not isinstance(expected_current, FileRevision):
        raise AtomicWriteError("expected_current must be a file revision")
    target.parent.mkdir(parents=True, exist_ok=True)
    lock_path = target.with_name(target.name + ".lock")
    lock_fd = os.open(lock_path, os.O_RDWR | os.O_CREAT, 0o600)
    candidate: Path | None = None
    try:
        fcntl.flock(lock_fd, fcntl.LOCK_EX)
        try:
            prior_bytes, current_revision = _read_file_with_revision(target)
        except OSError as exc:
            raise AtomicWriteError(f"cannot read atomic write target {target}: {exc}") from exc
        if expected_current is not None and current_revision != expected_current:
            raise AtomicWriteError(f"atomic write target changed since it was read: {target}")
        prior_mode = current_revision.mode
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=target.parent, prefix=target.name + ".candidate.", delete=False) as handle:
            candidate = Path(handle.name)
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        candidate_stat = candidate.stat(follow_symlinks=False)
        backup: Path | None = None
        if prior_bytes is not None:
            if prior_mode is None:
                raise AtomicWriteError(f"atomic write target has no captured mode: {target}")
            if backup_count:
                for number in range(backup_count - 1, 0, -1):
                    source = target.with_name(target.name + f".bak.{number}")
                    if source.exists():
                        os.replace(source, target.with_name(target.name + f".bak.{number + 1}"))
                backup = target.with_name(target.name + ".bak.1")
                _secure_backup_copy(prior_bytes, prior_mode, backup)
        os.replace(candidate, target)
        candidate = None
        target_digest = hashlib.sha256(content.encode("utf-8")).hexdigest()
        directory_fd = os.open(target.parent, os.O_RDONLY | os.O_DIRECTORY)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
        return AtomicWrite(
            target,
            target.parent / (target.name + ".candidate.committed"),
            backup,
            prior_bytes,
            prior_mode,
            hashlib.sha256(prior_bytes).hexdigest() if prior_bytes is not None else None,
            candidate_stat.st_dev,
            candidate_stat.st_ino,
            target_digest,
        )
    except OSError as exc:
        raise AtomicWriteError(f"atomic write failed for {target}: {exc}") from exc
    finally:
        if candidate is not None:
            candidate.unlink(missing_ok=True)
        fcntl.flock(lock_fd, fcntl.LOCK_UN)
        os.close(lock_fd)


def restore_atomic_write(write: AtomicWrite) -> None:
    """Restore the exact file state that preceded an atomic managed write."""

    target = write.target
    lock_path = target.with_name(target.name + ".lock")
    try:
        lock_fd = os.open(lock_path, os.O_RDWR | os.O_CREAT, 0o600)
    except OSError as exc:
        raise AtomicWriteError(f"cannot lock rollback target {target}: {exc}") from exc
    try:
        fcntl.flock(lock_fd, fcntl.LOCK_EX)
        try:
            _current_bytes, current_revision = _read_file_with_revision(target)
        except OSError as exc:
            raise AtomicWriteError(f"cannot verify rollback target {target}: {exc}") from exc
        if (
            write.target_device is None
            or write.target_inode is None
            or write.target_digest is None
            or not current_revision.exists
            or current_revision.device != write.target_device
            or current_revision.inode != write.target_inode
            or current_revision.digest != write.target_digest
        ):
            raise AtomicWriteError(f"rollback target changed since atomic write: {target}")
        try:
            if write.prior_bytes is None:
                target.unlink()
            else:
                if (
                    write.prior_mode is None
                    or write.prior_digest is None
                    or hashlib.sha256(write.prior_bytes).hexdigest() != write.prior_digest
                ):
                    raise AtomicWriteError(f"rollback snapshot changed since atomic write: {target}")
                restored: Path | None = None
                try:
                    with tempfile.NamedTemporaryFile(
                        "wb", dir=target.parent, prefix=target.name + ".restore.", delete=False
                    ) as restored_handle:
                        restored = Path(restored_handle.name)
                        restored_handle.write(write.prior_bytes)
                        os.fchmod(restored_handle.fileno(), write.prior_mode)
                        restored_handle.flush()
                        os.fsync(restored_handle.fileno())
                    os.replace(restored, target)
                    restored = None
                finally:
                    if restored is not None:
                        restored.unlink(missing_ok=True)
            directory_fd = os.open(target.parent, os.O_RDONLY | os.O_DIRECTORY)
            try:
                os.fsync(directory_fd)
            finally:
                os.close(directory_fd)
        except OSError as exc:
            raise AtomicWriteError(f"cannot restore rollback snapshot for {target}: {exc}") from exc
    finally:
        fcntl.flock(lock_fd, fcntl.LOCK_UN)
        os.close(lock_fd)


def discard_atomic_write(write: AtomicWrite) -> None:
    """Accept an in-memory rollback snapshot; no filesystem cleanup is needed."""


def _reload_and_wait(client: Any, timeout: float) -> None:
    """Subscribe first so the reload event cannot race the command request."""

    with client.subscribe(["workspace"]) as subscription:
        client.command("reload")
        subscription.wait_for(lambda _kind, body: body.get("change") == "reload", timeout)


def reload_with_rollback(client: Any, restore: Any, *, timeout: float = 5.0) -> ReloadResult:
    """Confirm Sway's reload event, or restore the prior include and reload it."""

    if not isinstance(timeout, (int, float)) or isinstance(timeout, bool) or timeout <= 0:
        raise ReloadRollbackError("reload timeout must be positive")
    try:
        _reload_and_wait(client, float(timeout))
        return ReloadResult(True, False)
    except Exception as original:
        try:
            restore()
            _reload_and_wait(client, float(timeout))
        except Exception as rollback_error:
            raise ReloadRollbackError(
                f"reload failed ({original}); rollback reload also failed ({rollback_error})"
            ) from rollback_error
        return ReloadResult(False, True, str(original))
