"""Pure, stdlib-only building blocks for plugin-owned Sway configuration.

The module deliberately has no knowledge of model handlers or user configuration
locations.  Callers supply every path and every side-effecting dependency.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from collections.abc import Mapping
from typing import Any

_MANAGED_MARKER = "# hermes-sway-plugin: managed-v1"
_METADATA_PREFIX = "# hermes-sway-plugin: metadata="
_DIGEST_PREFIX = "# hermes-sway-plugin: sha256="


class PersistentConfigError(Exception):
    """Base failure for a plugin-owned configuration operation."""


class ConfigFormatError(PersistentConfigError):
    """The include is not a complete managed include."""


class ManualEditRefused(PersistentConfigError):
    """The managed body differs from the body last generated by the plugin."""


class CriteriaError(PersistentConfigError):
    """A declarative window matcher cannot be represented safely by Sway."""


@dataclass(frozen=True)
class ManagedConfig:
    """The verified metadata and Sway body from one managed include."""

    metadata: dict[str, Any]
    body: str
    digest: str


def _canonical_metadata(metadata: Mapping[str, Any]) -> str:
    if not isinstance(metadata, Mapping):
        raise ConfigFormatError("managed metadata must be an object")
    try:
        return json.dumps(dict(metadata), ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    except (TypeError, ValueError) as exc:
        raise ConfigFormatError("managed metadata is not JSON serializable") from exc


def _body_digest(body: str) -> str:
    return hashlib.sha256(body.encode("utf-8")).hexdigest()


def render_managed_config(body: str, metadata: Mapping[str, Any]) -> str:
    """Render a deterministic, tamper-evident managed Sway include.

    The digest protects the emitted Sway body.  Metadata is canonical JSON so a
    future writer can safely compare it without depending on mapping order.
    """

    if not isinstance(body, str):
        raise ConfigFormatError("managed body must be a string")
    if "\x00" in body:
        raise ConfigFormatError("managed body cannot contain NUL")
    metadata_text = _canonical_metadata(metadata)
    return "\n".join(
        (
            _MANAGED_MARKER,
            _METADATA_PREFIX + metadata_text,
            _DIGEST_PREFIX + _body_digest(body),
            "",
            body,
        )
    )


def parse_managed_config(text: str) -> ManagedConfig:
    """Parse a renderer-produced include and refuse a manually changed body."""

    if not isinstance(text, str):
        raise ConfigFormatError("managed config must be text")
    header, separator, body = text.partition("\n\n")
    if not separator:
        raise ConfigFormatError("managed config is missing its header separator")
    lines = header.splitlines()
    if len(lines) != 3 or lines[0] != _MANAGED_MARKER:
        raise ConfigFormatError("managed config has an invalid header")
    if not lines[1].startswith(_METADATA_PREFIX) or not lines[2].startswith(_DIGEST_PREFIX):
        raise ConfigFormatError("managed config has an invalid metadata header")
    metadata_text = lines[1][len(_METADATA_PREFIX) :]
    try:
        metadata = json.loads(metadata_text)
    except json.JSONDecodeError as exc:
        raise ConfigFormatError("managed metadata is not valid JSON") from exc
    if not isinstance(metadata, dict) or _canonical_metadata(metadata) != metadata_text:
        raise ConfigFormatError("managed metadata is not canonical JSON object")
    digest = lines[2][len(_DIGEST_PREFIX) :]
    if len(digest) != 64 or any(char not in "0123456789abcdef" for char in digest):
        raise ConfigFormatError("managed config has an invalid sha256 digest")
    if _body_digest(body) != digest:
        raise ManualEditRefused("manual edit refused: managed Sway body checksum differs")
    return ManagedConfig(metadata=metadata, body=body, digest=digest)


# Short aliases keep the format API readable for callers which treat the include
# as a document rather than as a configuration object.
render_managed = render_managed_config
parse_managed = parse_managed_config


_CRITERIA_ORDER = (
    "app_id",
    "class",
    "instance",
    "title",
    "window_role",
    "window_type",
    "shell",
    "con_mark",
)
_CRITERIA_KEYS = frozenset(_CRITERIA_ORDER)
_PCRE_EXACT_SPECIALS = frozenset("\\.^$*+?{}[]|()")


def _escape_exact_pcre(value: str) -> str:
    return "".join("\\" + char if char in _PCRE_EXACT_SPECIALS else char for char in value)


def _sway_quoted(value: str) -> str:
    if "\x00" in value or "\n" in value or "\r" in value:
        raise CriteriaError("criterion value cannot contain a line break or NUL")
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render_criteria(match: Mapping[str, Any]) -> str:
    """Render stable Sway criteria from explicit exact or regular-expression values.

    Exact text becomes an anchored PCRE expression.  ``regex`` deliberately
    leaves PCRE metacharacters intact, while both modes quote for Sway's config
    grammar rather than for a shell.
    """

    if not isinstance(match, Mapping) or not match:
        raise CriteriaError("at least one criterion is required")
    unknown = set(match) - _CRITERIA_KEYS
    if unknown:
        raise CriteriaError(f"unsupported criterion key: {sorted(unknown)[0]}")
    parts: list[str] = []
    for key in _CRITERIA_ORDER:
        if key not in match:
            continue
        specification = match[key]
        if isinstance(specification, str):
            value, mode = specification, "exact"
        elif isinstance(specification, Mapping):
            value = specification.get("value")
            mode = specification.get("mode", "exact")
            if set(specification) - {"value", "mode"}:
                raise CriteriaError(f"criterion {key} contains unsupported fields")
        else:
            raise CriteriaError(f"criterion {key} must be an object")
        if not isinstance(value, str) or not value:
            raise CriteriaError(f"criterion {key} value must be a non-empty string")
        if mode not in {"exact", "regex"}:
            raise CriteriaError(f"criterion {key} mode must be exact or regex")
        expression = "^" + _escape_exact_pcre(value) + "$" if mode == "exact" else value
        parts.append(f'{key}="{_sway_quoted(expression)}"')
    return "[" + " ".join(parts) + "]"


render_match_criteria = render_criteria
